![imagen](./img/ejercicios.png)

In [1]:
import numpy as np

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [2]:
my_array = np.arange(10)
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
print(my_array[::-2])

[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [6]:
print(my_array)
print(my_array[-2:-4:-1])

[0 1 2 3 4 5 6 7 8 9]
[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [8]:
print(my_array)
print(my_array[2::-1])

[0 1 2 3 4 5 6 7 8 9]
[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [10]:
my_matrix = np.arange(1,21).reshape(4,5)
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [11]:
print(my_matrix[::-1,::-1])

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


In [13]:
print(np.flip(my_matrix))

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [14]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [15]:
print(my_matrix[:2,:2])

[[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [16]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [17]:
print(my_matrix[::2,::2])

[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [18]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [19]:
print(my_matrix[:3,::-1])

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


#### Ejemplo con array 3d

In [22]:
array_3d = np.arange(24).reshape(3,4,2)
print(array_3d)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]


In [25]:
array_3d[::2,:2,1:]

array([[[ 1],
        [ 3]],

       [[17],
        [19]]])

## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [27]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
print(x)

['Loro' 'Perro' 'Gato' 'Loro' 'Perro']


In [30]:
print(x == "Loro")

[ True False False  True False]


In [31]:
print(x[x == "Loro"])

['Loro' 'Loro']


In [35]:
np.where(x == "Loro")

(array([0, 3], dtype=int64),)

In [38]:
x[np.where(x == "Loro")]

array(['Loro', 'Loro'], dtype='<U5')

## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [39]:
x = np.arange(20).reshape(2,5,2)
print(x)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


In [42]:
print(x.ndim)
print(x.shape)
print(x.size)

3
(2, 5, 2)
20


## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [43]:
print(my_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [44]:
print(my_matrix[::-1,::-1])

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [51]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [52]:
print(x.itemsize) # Cada elemento
print(x.nbytes) # Todo el array
print(x.dtype)

8
80
float64


In [63]:
x = np.zeros(10, dtype=np.int8)
print(x)

[0 0 0 0 0 0 0 0 0 0]


In [64]:
print(x.itemsize) # Cada elemento
print(x.nbytes) # Todo el array
print(x.dtype)

1
10
int8


In [65]:
x[3] = 1
print(x)

[0 0 0 1 0 0 0 0 0 0]


## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [67]:
x = np.arange(10,50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [68]:
print(x[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [69]:
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


## Ejercicio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [71]:
ejer_13 = np.array([1,2,0,0,4,0])
print(type(ejer_13))

<class 'numpy.ndarray'>


In [74]:
np.where(ejer_13 != 0)

(array([0, 1, 4], dtype=int64),)

In [73]:
ejer_13[np.where(ejer_13 != 0)]

array([1, 2, 4])

In [86]:
(ejer_13 != 0) & (ejer_13 % 2 == 0)

array([False,  True, False, False,  True, False])

In [83]:
ejer_13[(ejer_13 != 0) & (ejer_13 % 2 == 0)]

array([2, 4])

In [82]:
ejer_13[np.where((ejer_13 != 0) & (ejer_13 % 2 == 0))]

array([2, 4])

In [89]:
def ejercicio_13(vector):
    return np.where(vector != 0)

In [92]:
print(ejercicio_13(np.array([2,7,0,2])))
print(ejercicio_13(np.array([0,7,0,2])))

(array([0, 1, 3], dtype=int64),)
(array([1, 3], dtype=int64),)


## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [117]:
np.random.seed(20)
x = np.random.randint(100, size=(10,10))
print(x)
# print(min(x))
print(np.min(x))
print(x.min())
print(np.max(x))
print(x.max())

[[99 90 15 95 28 90  9 20 75 22]
 [71 34 96 40 85 90 26 83 16 62]
 [16  7 98  6 26 13 75 58 25  3]
 [74 75 61 77 83 57 94 32 10  6]
 [75 18  3 77 17 43 16 18 79 90]
 [59 71 75 29 45  6 63 78 24 18]
 [93 33 78 42 94  3 18 70 52 22]
 [14  4 27 75  8  6 26 79 82 78]
 [10 33 85 17 40 82 42 60 84 30]
 [36  8 48 19 48 95 53 10 38  9]]
3
3
99
99


## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [124]:
x = np.random.random(30)
print(x)

[0.73647103 0.9706047  0.68136272 0.490452   0.12840324 0.50383093
 0.4096691  0.25559738 0.61806603 0.89501445 0.66750239 0.57585336
 0.64872048 0.96107677 0.86436925 0.78272878 0.31110332 0.27191386
 0.95738054 0.51644268 0.41742553 0.63886307 0.68952736 0.76848649
 0.44285459 0.95131449 0.53279129 0.31356138 0.20352206 0.98534762]


In [127]:
print(x.sum()/len(x))

0.6063418956707508


In [128]:
print(x.mean())
print(np.mean(x))

0.6063418956707508
0.6063418956707508


## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [129]:
ejer_16 = np.ones((4,4))
print(ejer_16)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [133]:
print(ejer_16[1:3,1:3])

[[1. 1.]
 [1. 1.]]


In [134]:
ejer_16[1:3,1:3] = 0
print(ejer_16)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [135]:
ejer_16 = np.zeros((4,4))
print(ejer_16)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [137]:
ejer_16[::3] = 1
print(ejer_16)

[[1. 1. 1. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 1. 1.]]


In [139]:
ejer_16[1:3,::3] = 1

In [140]:
print(ejer_16)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [142]:
def ejercicio_16(tamaño):
    x = np.ones((tamaño,tamaño))
    x[1:-1,1:-1] = 0
    return x

In [146]:
print(ejercicio_16(20))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [147]:
x = np.zeros((8,8))
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [149]:
x[::2,1::2] = 1
x[1::2,::2] = 1
print(x)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [162]:
x = np.zeros((8,8))
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [167]:
for i in x:
    print(i)

[0. 1. 0. 1. 0. 1. 0. 1.]
[1. 0. 1. 0. 1. 0. 1. 0.]
[0. 1. 0. 1. 0. 1. 0. 1.]
[1. 0. 1. 0. 1. 0. 1. 0.]
[0. 1. 0. 1. 0. 1. 0. 1.]
[1. 0. 1. 0. 1. 0. 1. 0.]
[0. 1. 0. 1. 0. 1. 0. 1.]
[1. 0. 1. 0. 1. 0. 1. 0.]


In [168]:
for i in range(len(x)):
    for j in range(len(x[i])):
        if (i % 2 == 0) & (j % 2 != 0) | (i % 2 != 0) & (j % 2 == 0):
            x[i][j] = 1

print(x)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [169]:
a = np.array([[0,1],[1,0]])
print(a)

[[0 1]
 [1 0]]


In [172]:
x = np.tile(a, (4,4))
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 19
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [176]:
x = np.random.randint(1,20, (5,5))
print(x)

[[ 1  9  9 18 12]
 [17 10 14 19  3]
 [ 5  2 14 14 13]
 [12 17  4  9  1]
 [17  6 19  3  4]]


In [177]:
# Normalizar
x = (x - np.mean(x)) / np.std(x)
print(x)

[[-1.53231541 -0.18225778 -0.18225778  1.33655706  0.32401383]
 [ 1.16779985 -0.01350058  0.66152824  1.50531426 -1.194801  ]
 [-0.8572866  -1.36355821  0.66152824  0.66152824  0.49277104]
 [ 0.32401383  1.16779985 -1.0260438  -0.18225778 -1.53231541]
 [ 1.16779985 -0.68852939  1.50531426 -1.194801   -1.0260438 ]]


In [179]:
print(x.mean())
print(x.std())

8.881784197001253e-18
0.9999999999999999


## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [180]:
x = np.arange(11)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [181]:
y = x.copy()
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [183]:
y[(y > 3) & (y < 8)] = -1
print(y)

[ 0  1  2  3 -1 -1 -1 -1  8  9 10]


In [185]:
z = x.copy()
z[(z > 3) & (z < 8)] *= -1

In [186]:
print(z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]
